<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="login.css">
    <title>Store</title>
</head>
<body>
    <div class="edit">
        <script>
            $(".bar").click(function () {
            var effect = 'slide';
            var options = { direction: right};
            var duration = 500;
            $('edit').toggle(effect, options, duration);
            });
        </script>
        <div class="bar"></div>
            <div class="name">
                <?php
                    echo $_POST['login']. '<br>'. $_POST['passwd'];
                ?>
            </div>
            <hr>
        </div>
        <div class="items">

        </div>
</body>
</html>