<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="login.css">
    <title>Store</title>
</head>
<body>
    <div class="edit">
        <script>
            $(".bar").click(function () {
            var effect = 'slide';
            var options = { direction: right};
            var duration = 500;
            $('edit').toggle(effect, options, duration);
            });
        </script>
        <div class="bar"></div>
            <div class="name">
                <?php
                    echo $_POST['login']. '<br>'. $_POST['passwd'];
                ?>
            </div>
            <hr>
        </div>
        <div class="items">
        <div class="items">
            <?php
            $i  = 0;
            $uploads_dir = "./uploads";
            $array = array(1 => "batman/*.*", 2 => "counterstike/*.*", 3 => "food/*.*", 4 => "tech/*.*", 5 => "emoji/*.*", 6 => "monsters/*.*");
            $rnd = array_rand($array, 3);
            $all = $uploads_dir."/".$array[$rnd];
            print_r($all);
            foreach ($all as $key)
            {
                echo    "<div class='gallery'>";
                echo        '<a target="_blank" href="#">';
                echo            '<img src="'.$key.'" alt="Cinque Terre" width="300px" height="200px">';
                echo        '</a>';
                echo        '<div class="desc">Add a description of the image here</div>';
                echo        '<div class="add_cart"></div>';
                echo    '</div>';
            }
            ?>
        </div>
        </div>
</body>
</html>